CREATE DATABASE SummitRTS;
use SummitRTS;

SET default_storage_engine=INNODB;

CREATE TABLE STATUS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Status varchar(50) NOT NULL,
  HtmlColor varchar(10) Not NULL,
  HTML_Description varchar(20) Not NULL,
  PRIMARY KEY (ID),
  UNIQUE (Status),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE STATUS AUTO_INCREMENT=100;

CREATE TABLE TEST_RESULT (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(50) NOT NULL,
  HtmlColor varchar(10) Not NULL,
  HTML_Description varchar(20) Not NULL,
  PRIMARY KEY (ID),
  UNIQUE (Name),
  UNIQUE (HtmlColor),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE TEST_RESULT AUTO_INCREMENT=100;

CREATE TABLE QUEUE_MANAGER (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Status_ID int(11) NOT NULL,
  Wait int(11) NOT NULL,
  Log_File varchar(255),
  PRIMARY KEY (ID),
  FOREIGN KEY(Status_ID) REFERENCES STATUS(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE RTS_PROPERTIES (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(200) NOT NULL,
  Val varchar(500),
  PRIMARY KEY (ID),
  UNIQUE (Name),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SOFTWARE (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Manufacturer varchar(100) NOT NULL,
  Name varchar(100) NOT NULL,
  Version varchar(25) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT UK_SOFTWARE UNIQUE (Manufacturer,Name,Version),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE VM_TEMPLATES (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Ref_Name varchar(100) NOT NULL,
  OS varchar(100) NOT NULL,
  OS_Type varchar(100) NOT NULL,
  OS_Version varchar(50) NOT NULL,
  OS_Service_Pack varchar(50) NOT NULL,
  OS_Arch varchar(10) NOT NULL,
  OS_User_Name varchar(100) NOT NULL,
  OS_User_PWD varchar(100) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (Ref_Name),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE AVAILABLE_SOFTWARE (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Software_ID int(11) NOT NULL,
  VM_Template_ID int(11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY(VM_Template_ID) REFERENCES VM_TEMPLATES(ID),
  FOREIGN KEY(Software_ID) REFERENCES SOFTWARE(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE HYPERVISOR_TYPES (
  ID int(11) NOT NULL,
  Name varchar(30) NOT NULL,
  PRIMARY KEY (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE HYPERVISORS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Hypervisor_Type_ID int(11) NOT NULL,
  IP_Address varchar(15) NOT NULL,
  Username varchar(100) NOT NULL,
  Password varchar(100) NOT NULL,
  Version varchar(20) NOT NULL,
  Mgmt_IP varchar(100),
  Datacenter varchar(100) NOT NULL,
  Datastore varchar(100) NOT NULL,
  Status_ID int(11) NOT NULL default 11,
  Max_Concurrent_SUTS int(3) NOT NULL,
  Description varchar(1000),
  PRIMARY KEY (ID),
  UNIQUE (IP_Address),
  FOREIGN KEY (Hypervisor_Type_ID) REFERENCES HYPERVISOR_TYPES(ID),
  FOREIGN KEY(Status_ID) REFERENCES STATUS(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE HYPERVISOR_VMS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Hypervisor_ID int(11) NOT NULL,
  VM_Template_ID int(11) NOT NULL,
  Status_ID int(11) NOT NULL default 11,
  Tools_Available int(1) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY(Hypervisor_ID) REFERENCES HYPERVISORS(ID),
  FOREIGN KEY(VM_Template_ID) REFERENCES VM_TEMPLATES(ID),
  FOREIGN KEY(Status_ID) REFERENCES STATUS(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE WORKFLOWS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(30) NOT NULL,
  Script_Path varchar(100) NOT NULL,
  Primary Key (ID),
  UNIQUE (Name),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE AGENT_MANAGERS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  IP_Address varchar(15) NOT NULL,
  Status_ID int(11) NOT NULL,
  Wait int(11) NOT NULL,
  Logfile varchar(100) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (IP_Address),
  FOREIGN KEY (Status_ID) REFERENCES STATUS(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE AVAILABLE_WORKFLOWS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Agent_Mgr_ID int(11) NOT NULL,
  Hypervisor_Type_ID int(11) NOT NULL,
  Workflow_ID int(11) NOT NULL,
  Status_ID int(11) NOT NULL default 11,
  PRIMARY KEY (ID),
  FOREIGN KEY (Agent_Mgr_ID) REFERENCES AGENT_MANAGERS(ID),
  FOREIGN KEY (Hypervisor_Type_ID) REFERENCES HYPERVISOR_TYPES(ID),
  FOREIGN KEY (Workflow_ID) REFERENCES WORKFLOWS(ID),
  FOREIGN KEY(Status_ID) REFERENCES STATUS(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TEST_SUITES (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(255) NOT NULL,
  Status_ID int(11) NOT NULL,
  Total_SUT int(3),
  PRIMARY KEY (ID),
  UNIQUE (Name),
  FOREIGN KEY (Status_ID) REFERENCES STATUS(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SUT_TYPE (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(20) NOT NULL,
  UNIQUE (Name),
  PRIMARY KEY (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SUTs (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(100) NOT NULL,
  Status_ID int(11) NOT NULL,
  Test_Suite_ID int(11) NOT NULL,
  VM_Template_ID int(11) NOT NULL,
  Hypervisor_Type_ID int(11) NOT NULL, 
  Hypervisor_ID int(11),
  Agent_Manager_ID int(11),
  Workflow_ID int(11) NOT NULL,
  SUT_Type_ID int(11) NOT NULL,
  Log_File varchar(500),
  IP_Address varchar(15),
  Remote_Console_URL varchar(255),
  Console_Active int(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  UNIQUE (Name),
  FOREIGN KEY(Status_ID) REFERENCES STATUS(ID), 
  FOREIGN KEY(Test_Suite_ID) REFERENCES TEST_SUITES(ID),
  FOREIGN KEY(VM_Template_ID) REFERENCES VM_TEMPLATES(ID),
  FOREIGN KEY (Hypervisor_Type_ID) REFERENCES HYPERVISOR_TYPES(ID),
  FOREIGN KEY (Hypervisor_ID) REFERENCES HYPERVISORS(ID),
  FOREIGN KEY (Agent_Manager_ID) REFERENCES AGENT_MANAGERS(ID),
  FOREIGN KEY (Workflow_ID) REFERENCES WORKFLOWS(ID),
  FOREIGN KEY (SUT_Type_ID) REFERENCES SUT_TYPE(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TEST_CASES (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(255) NOT NULL,
  SUT_ID int(11) NOT NULL,
  Status_ID int(11) NOT NULL,
  Result_ID int(11),
  Order_Index int(11) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT UK_TEST_CASES UNIQUE (Name,SUT_ID),
  FOREIGN KEY(SUT_ID) REFERENCES SUTS(ID), 
  FOREIGN KEY(Status_ID) REFERENCES STATUS(ID), 
  FOREIGN KEY(Result_ID) REFERENCES TEST_RESULT(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TEST_CASE_SCRIPTS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Script_Path varchar(255) NOT NULL,
  Test_Case_ID int(11) NOT NULL,
  Order_Index int(11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY(Test_Case_ID) REFERENCES TEST_CASES(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TEST_CASE_LOG_FILES (
  ID int(11) NOT NULL AUTO_INCREMENT ,
  Test_Case_ID int(11) NOT NULL,
  Log_Path varchar(500) NOT NULL,
  Log_File_Name varchar(100) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY(Test_Case_ID) REFERENCES TEST_CASES(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
